### ISSUE TITLE
How to use this properly in an AEM project?

### ISSUE THREAD

**Issue by pristinetran** [gavoja/runna-webserver#1]
As the title suggests, I post these questions in the other repo (aemsync).

Assume I'm running aemsync in 1 cli
If I open another cli and do the following, would it work?
`runa-webserver -p localhost:4502`

-----------------
I then tried to change it to:

`runna-webserver -p 4502 -w /Users/admin/Dev/AEMcontainer/AEM/Author/crx-quickstart`

Running that, I have the following error:

Error: ENOENT: no such file or directory, stat
'/Users/admin/Dev/IVC/secondProj/Users/admin/Dev/AEMcontainer/AEM/Author/crx-quickstart/crx/packmgr/service.jsp'
at Error (native)

Replacing -w flag with this: /Users/admin/Dev/IVC/secondProj/firstProj/ica/ui.apps/src/main/content/jcr_root, I have the same error.

**Comment by gavoja** [comment]
This is not an AEM tool, it is an HTTP server with auto-reload functionality.
